{
 "title": "DSS - resources",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Service resource consumed per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 13), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from service a,service_report b where a.id = b.service_id and b.category='resource-usage' and jhi_key='cpu_millicore' group by time, a.name order by 1 asc,2,3"
    },
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 13), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from service a,service_report b where a.id = b.service_id and b.category='resource-usage' and jhi_key='cpu_millicore' group by time, a.name order by 1 asc,2,3"
    }
   ]
  },
  {
   "title": "Service resource consumed per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 16), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from service a,service_report b where a.id = b.service_id and b.category='resource-usage' and jhi_key='cpu_millicore' group by time, a.name order by 1 asc,2,3"
    },
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 16), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from service a,service_report b where a.id = b.service_id and b.category='resource-usage' and jhi_key='cpu_millicore' group by time, a.name order by 1 asc,2,3"
    }
   ]
  },
  {
   "title": "Service resource requested per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 13), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from service a,service_report b where a.id = b.service_id and b.category='max_request' and jhi_key='cpu_millicore' group by time, a.name order by 1 desc,2,3"
    },
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 13), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [memory_mb]'),round(avg(b.value)) as 'memory_mb' from service a,service_report b where a.id = b.service_id and b.category='max_request' and jhi_key='memory_mb' group by time, a.name order by 1 desc,2,3"
    }
   ]
  },
  {
   "title": "Service resource requested per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 16), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from service a,service_report b where a.id = b.service_id and b.category='max_request' and jhi_key='cpu_millicore' group by time, a.name order by 1 desc,2,3"
    },
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 16), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [memory_mb]'),round(avg(b.value)) as 'memory_mb' from service a,service_report b where a.id = b.service_id and b.category='max_request' and jhi_key='memory_mb' group by time, a.name order by 1 desc,2,3"
    }
   ]
  },
  {
   "title": "Node resource consumed per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 13), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from node a,node_report b where a.id = b.node_id and jhi_key='cpu_millicore' group by time, a.name order by 1 desc,2,3"
    },
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 13), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [memory_mb]'),round(avg(b.value)) as 'memory_mb' from node a,node_report b where a.id = b.node_id and jhi_key='memory_mb' group by time, a.name order by 1 desc,2,3"
    }
   ]
  },
  {
   "title": "Node resource consumed per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 16), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [cpu_millicore]'),round(avg(b.value)) as 'cpu_millicore' from node a,node_report b where a.id = b.node_id and jhi_key='cpu_millicore' group by time, a.name order by 1 desc,2,3"
    },
    {
     "rawSql": "select UNIX_TIMESTAMP(STR_TO_DATE(substring(b.timestamp,1, 16), '%Y-%m-%d %H:%i:%s')) as time ,concat(a.name,' [memory_mb]'),round(avg(b.value)) as 'memory_mb' from node a,node_report b where a.id = b.node_id and jhi_key='memory_mb' group by time, a.name order by 1 desc,2,3"
    }
   ]
  }
 ]
}