apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confservice-data
  namespace: core
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-sc-retain
