apiVersion: apps/v1
kind: Deployment
metadata:
  name: confservice-mysql
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confservice-mysql
  template:
    metadata:
      labels:
        app: confservice-mysql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: confservice-data
      containers:
        - name: mysql
          image: mysql:5.6.39
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: confservice
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: confservice-mysql
  namespace: core
spec:
  selector:
    app: confservice-mysql
  ports:
    - port: 3306
