apiVersion: v1
kind: Service
metadata:
  name: confservice
  namespace: core
  labels:
    app: confservice
spec:
  selector:
    app: confservice
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30288
