export const enum ExecStatus {
  RUNNING = 'RUNNING',

  STOPPED = 'STOPPED',

  ERROR = 'ERROR',

  STARTING = 'STARTING',

  STOPPING = 'STOPPING',

  FORCE_STOP = 'FORCE_STOP',

  SCALING_MORE_RESOURCES = 'SCALING_MORE_RESOURCES',

  SCALING_LESS_RESOURCES = 'SCALING_LESS_RESOURCES',

  OFFLOADING_BETTER_RANKING = 'OFFLOADING_BETTER_RANKING',

  OFFLOADING_WORSE_RANKING = 'OFFLOADING_WORSE_RANKING',
}
