apiVersion: v1
kind: Service
metadata:
  name: confservicedss-nodered
  namespace: core
  labels:
    app: confservicedss-nodered
spec:
  selector:
    app: confservicedss-nodered
  type: NodePort
  ports:
    - name: http
      port: 1880
      nodePort: 31858
      targetPort: 1880
