version: "3.9"
services:
  basic-analytics-rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672"
    deploy:
      resources:
        limits:
          cpus: PLACEHOLDER_CPU_MILLICORE
          memory: PLACEHOLDER_MEMORY_MB
        reservations:
          cpus: PLACEHOLDER_CPU_MILLICORE
          memory: PLACEHOLDER_MEMORY_MB