apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-app-ve
  name: example-app-ve
  namespace: PLACEHOLDER_NAMESPACE
spec:
  replicas: PLACEHOLDER_REPLICAS
  selector:
    matchLabels:
      app: example-app-ve
  strategy: {}
  template:
    metadata:
      labels:
        app: example-app-ve
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - PLACEHOLDER_HOSTNAME
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do sleep 20; stress -m 20M -t 10; done;
        image: polinux/stress 
        name: stress
        resources:
          limits:
            cpu: PLACEHOLDER_CPU_MILLICOREm
            memory: PLACEHOLDER_MEMORY_MBMi
          requests:
            cpu: PLACEHOLDER_CPU_MILLICOREm
            memory: PLACEHOLDER_MEMORY_MBMi
