apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: delegated-app-ho
  name: delegated-app-ho
  namespace: PLACEHOLDER_NAMESPACE
spec:
  replicas: PLACEHOLDER_REPLICAS
  selector:
    matchLabels:
      app: delegated-app-ho
  strategy: {}
  template:
    metadata:
      labels:
        app: delegated-app-ho
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - PLACEHOLDER_HOSTNAME
      containers:
      - image: etiennetremel/nginx-prometheus 
        name: nginx
        resources:
          limits:
            cpu: PLACEHOLDER_CPU_MILLICOREm
            memory: PLACEHOLDER_MEMORY_MBMi
          requests:
            cpu: PLACEHOLDER_CPU_MILLICOREm
            memory: PLACEHOLDER_MEMORY_MBMi
